name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0, v2.1.3, etc.
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        # Add any other dependencies your project needs
        # sudo apt-get install -y gcc g++ make cmake etc.
        
    - name: Build project
      run: make
      
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
    - name: Create Release with Assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create ${{ steps.get_version.outputs.VERSION }} \
          --title "Release ${{ steps.get_version.outputs.VERSION }}" \
          --notes "Automated build from commit ${{ github.sha }}" \
          ./Main#Main
